"""Normalized jobs module."""

from modules.jobs.ai_normalization import (
    AINormalizationBatchItemResult,
    AINormalizationBatchOutput,
    AINormalizationBatchPromptInput,
    AINormalizationBatchPromptItem,
    AINormalizationContractError,
    AINormalizationPromptInput,
    NormalizationEndpointType,
    build_ai_normalization_batch_messages,
    build_ai_normalization_format_repair_messages,
    build_ai_normalization_messages,
    validate_ai_normalization_batch_output,
    validate_ai_normalization_output,
)
from modules.jobs.dates import NormalizedPostedDate, normalize_posted_date, parse_absolute_datetime
from modules.jobs.salary import NormalizedSalary, normalize_salary
from modules.jobs.schemas import (
    CanonicalJobSchema,
    CanonicalJobStatus,
    CompanySchema,
    EmploymentType,
    ExperienceLevel,
    LocationSchema,
    PresentationMetadataSchema,
    SalaryPeriod,
    SalarySchema,
    SourceMetadataSchema,
    SourcePlatform,
    WorkType,
)

__all__ = [
    "CanonicalJobSchema",
    "CanonicalJobStatus",
    "CompanySchema",
    "EmploymentType",
    "ExperienceLevel",
    "LocationSchema",
    "PresentationMetadataSchema",
    "SalaryPeriod",
    "SalarySchema",
    "SourceMetadataSchema",
    "SourcePlatform",
    "WorkType",
    "NormalizedSalary",
    "normalize_salary",
    "NormalizedPostedDate",
    "normalize_posted_date",
    "parse_absolute_datetime",
    "AINormalizationContractError",
    "AINormalizationBatchPromptItem",
    "AINormalizationBatchPromptInput",
    "AINormalizationBatchItemResult",
    "AINormalizationBatchOutput",
    "AINormalizationPromptInput",
    "NormalizationEndpointType",
    "build_ai_normalization_batch_messages",
    "build_ai_normalization_format_repair_messages",
    "build_ai_normalization_messages",
    "validate_ai_normalization_batch_output",
    "validate_ai_normalization_output",
]
