"""JobStreet source adapter."""

from integrations.sources.jobstreet.detail import (
    JOBSTREET_DETAIL_OPERATION,
    JOBSTREET_DETAIL_QUERY,
    JobStreetDetailAdapter,
    JobStreetDetailQuery,
    JobStreetDetailResult,
    build_jobstreet_detail_request_body,
    merge_jobstreet_list_and_detail,
    parse_jobstreet_detail_payload,
)
from integrations.sources.jobstreet.list import (
    JOBSTREET_DEFAULT_HEADERS,
    JOBSTREET_GRAPHQL_OPERATION,
    JOBSTREET_GRAPHQL_PATH,
    JOBSTREET_PUBLIC_DEFAULT_HEADERS,
    JOBSTREET_PUBLIC_JOB_BASE_URL,
    JOBSTREET_SEARCH_QUERY,
    JOBSTREET_SOURCE_PLATFORM,
    JobStreetListAdapter,
    JobStreetListQuery,
    JobStreetListResult,
    JobStreetPagination,
    RawSourceJob,
    build_jobstreet_default_headers,
    build_jobstreet_http_client,
    build_jobstreet_list_request_body,
    build_jobstreet_public_headers,
    build_jobstreet_public_http_client,
    build_jobstreet_source_url,
    extract_jobstreet_source_timestamp,
    parse_jobstreet_list_payload,
)
from integrations.sources.jobstreet.mapper import map_jobstreet_job

__all__ = [
    "JOBSTREET_DEFAULT_HEADERS",
    "JOBSTREET_DETAIL_OPERATION",
    "JOBSTREET_DETAIL_QUERY",
    "JOBSTREET_GRAPHQL_OPERATION",
    "JOBSTREET_GRAPHQL_PATH",
    "JOBSTREET_PUBLIC_DEFAULT_HEADERS",
    "JOBSTREET_PUBLIC_JOB_BASE_URL",
    "JOBSTREET_SEARCH_QUERY",
    "JOBSTREET_SOURCE_PLATFORM",
    "JobStreetDetailAdapter",
    "JobStreetDetailQuery",
    "JobStreetDetailResult",
    "JobStreetListAdapter",
    "JobStreetListQuery",
    "JobStreetListResult",
    "JobStreetPagination",
    "RawSourceJob",
    "build_jobstreet_default_headers",
    "build_jobstreet_detail_request_body",
    "build_jobstreet_http_client",
    "build_jobstreet_list_request_body",
    "build_jobstreet_public_headers",
    "build_jobstreet_public_http_client",
    "build_jobstreet_source_url",
    "extract_jobstreet_source_timestamp",
    "merge_jobstreet_list_and_detail",
    "map_jobstreet_job",
    "parse_jobstreet_detail_payload",
    "parse_jobstreet_list_payload",
]
